site_name: Extended Local States

theme:
  name: material

  features:
    - navigation.tabs
    - navigation.sections

  nav:
    - Home: index.md


    - Artigos:
      - Buscemi: buscemi2012all.md
      - Werner: werner1989quantum.md
      - Hrushowski: hrushovski2004generalizations.md


    - Registro de Reuniões: log.md


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
